# Site settings
name: Welcome! How are you
email: xiaoyu.lu0405@gmail.com
author: 晓宇Lu
url: https://lxyu0405.github.io/blog/
resume_site: https://lxyu0405.github.io/blog/
github: https://github.com/lxyu0405/
baseurl: ""
description: I'm fine, thank you! And you?   ——   套路
meta_description: 晓宇Lu;个人博客;技术;
motto: To be a better man... Orzzz
banner: 但愿厚积薄发

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/

gems: [jekyll-paginate]
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lxyu0405
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : lxyu0405
    duoshuo:
        short_name : lxyu0405
    disqus :
        short_name : lxyu0405
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light